### ISSUE TITLE
Feature Request: Add a filter icon to the column name

### ISSUE THREAD

**Issue by slms-cloud** [X2CommunityCore/xcom2-launcher#100]
Hi,

I love the filtering feature of AML, but IMHO from the point of view of usability a "filter icon" should be added to the column name header to indicate if filtering is been applied on that column.

The filter icon can be something like this:
https://pngtree.com/free-icon/filter_767384

So for each column, you can have 4 display states:

1. A column shows: <"column name">
    Sort State: disabled (no sort icon)
    Filter State: disabled (no filter icon)

2. A column shows: <"column name"><"sort icon">
    Sort State: enabled, (show Ascending/Descending sort icon depending on sort mode)
    Filter State: disabled (no filter icon)

3. A columns shows: <"column name"><"filter icon">
    Sort State: disabled (no sort icon)
    Filter State: disabled (show filter icon, since filtering is been applied on this column)

4. A columns shows the <"column name"><"filter icon"><"sort icon">
    Sort State: enabled, (show ascending/descending icon depending on sort mode)
    Filter State: enabled (show filter icon, since filtering is been applied on this column)

NOTE: Left chick on the column header still toggles the sort order (AS IS)
NOTE: Right click on the column header still shows Filtering PopUp (AS IS)
NOTE: Sorting can only be applied to a single column (AS IS)
NOTE: Filtering can be applied to multiple columns (AS IS)
NOTE: If the user hides (unselect) a column from the Filtering PopUp, this automatically disabled sorting and clear all filters on that column (AS IS)

I believe this could be a nice feature and is relative easy to implement.

Regards,

Duck Vader

**Comment by RevZero** [comment]
To summarize: You are just suggesting to show a filter indicator on the column header, if filtering for that column is active?

**Comment by slms-cloud** [comment]
You interpretation is correct :)

**Comment by RevZero** [comment]
Then yes, we can have this in next release. As far as I know, the functionality is already there, only currently disabled.
