### ISSUE TITLE
Unable to individual enable/disable mod that share the same ID (State: Duplicate ID)

### ISSUE THREAD

**Issue by slms-cloud** [X2CommunityCore/xcom2-launcher#101]
AML does not allow to individually (enable/disable) mods that use the same "ID".
These mods are show in red with State: "Duplicated ID".

Since, AFAIK, it is impossible to individually enable/disable one of the conflicting mods it is not possible to launch XCOM 2 without Delete/Unsubscribe one of the mods... It is also impossible to create different AML profiles with just one of the mods since both get selected/unselected in the profile...

I'm not sure if this is a AML issue. If I try to use built-in XCOM 2 Laucher I can't select the mods individually too... I'm not sure if AML can do any type of "workaround" to solve this type of Duplicate ID issue...

EXAMPLE #1:  (Duplicated ID: X2WOTCCommunityHighlander)
* [BETA] X2WOTCCommunityHighlander
   https://steamcommunity.com/sharedfiles/filedetails/?id=1796402257
* X2WOTCCommunityHighlander
   https://steamcommunity.com/sharedfiles/filedetails/?id=1134256495

EXAMPLE #2: (Duplicated ID: ModConfigMenu)
* [WotC] Mod Config Menu
   https://steamcommunity.com/sharedfiles/filedetails/?id=667104300
* Mod Config Menu Legacy
   https://steamcommunity.com/sharedfiles/filedetails/?id=1122831824

Granted that the mod authors should use different ID for each mod version...

**Comment by Xymanek** [comment]
> it is not possible to launch XCOM 2 without Delete/Unsubscribe one of the mods...

No, the game can be launched, the only limitation is that both are either enabled or not

> It is also impossible to create different AML profiles with just one of the mods since both get selected/unselected in the profile

Profiles use the list of your active mods - as such the limitation comes from the previous point. Besides, profiles are just text files - you can easily remove 1 of the 2 lines yourself

> I'm not sure if AML can do any type of "workaround" to solve this type of Duplicate ID issue...

It cannot

**Comment by siath70** [comment]
I'm sorry but I would like to see this happen too. As with some mods you can not launch the game at all, it crashes.
The problem lies in that when you select one mod the other also gets activated too.
A good example for this would be a WOTC mod and a NON-WOTC mod that does the same thing.
I would rather a warning that there is a conflict, I hate having to delete mods (esp if they're big) just to play the game.
Something like do not have both of these mods activated at the same time, please choose one or the other.

Though I see your point, maybe the ability to edit a profile in the launcher would be nice.

**Comment by Xymanek** [comment]
> I would like to see this happen too

This is limitation of native XCOM2 code which is responsible for loading mods. The launcher cannot fix this

**Comment by Xymanek** [comment]
> I would like to see this happen too

This is limitation of native XCOM2 code which is responsible for loading mods. The launcher cannot fix this

**Comment by RevZero** [comment]
Was implemented with PR #175
