### ISSUE TITLE
False positive MCO conflicts when MCO lines are identical

### ISSUE THREAD

**Issue by robojumper** [X2CommunityCore/xcom2-launcher#102]
A few mods implement `X2Action_MoveClimbWall` with a MCO. In order to not conflict, they use the same class in the same package,

	[Engine.Engine]
	+ModClassOverrides=(BaseGameClass="X2Action_MoveClimbWall", ModClass="WallClimbOverride.X2Action_MoveClimbWall_Override")
	
and rely on the config parser to ignore duplicate lines (behavior when using `+`).

This throws a false positive because this behavior is not implemented in the AML config parser. Doing that would remove a common question about this particular false positive.

**Comment by RevZero** [comment]
Resolved in 144bffff6448bbe12275eab296d189de7fb68998.
