### ISSUE TITLE
INI editor - Unhandled Exception on Save (Specific cases)

### ISSUE THREAD

**Issue by kittykitty71** [X2CommunityCore/xcom2-launcher#120]
Specifically, this is happening if you hit save, but the file being edited happens to be set read-only (or if for whatever reason you don't have permissions to alter it).

While that's not exactly a "fault" in the Launcher, it might be nice to toss in some error-handling code for such situations to avoid the program crash that currently results in these cases.

**Comment by RevZero** [comment]
Please attach AML.log file.

**Comment by kittykitty71** [comment]
Had to go make it crash again to get logs.  lol

Here they are:
[AML.log](https://github.com/X2CommunityCore/xcom2-launcher/files/3612822/AML.log)
[error.log](https://github.com/X2CommunityCore/xcom2-launcher/files/3612823/error.log)
