### ISSUE TITLE
V1.2 - Mods only launch with XCOM2 not WOTC

### ISSUE THREAD

**Issue by IGdood** [X2CommunityCore/xcom2-launcher#15]
The mods only work when launching in XCOM2.  When launching in WOTC none of the mods load and the game is pure vanilla.

**Comment by BTernaryTau** [comment]
I'm not sure what would cause this. Anything abnormal about your setup?

**Comment by Littlebob86** [comment]
I'm having the same thing.. When using WotC none of the mods are working, I'm having to load through the base launcher :(

**Comment by SB-FM** [comment]
it happened to me on the first launch of the launcher. It displayed my list of mods just fine and wrote the modoptions.ini correctly as far as i could tell. Clicking the WotC Button started the right executable but without mods. Closed the game, restarted launcher and it worked the second time.

**Comment by IGdood** [comment]
@BTernaryTau By setup do you mean my computer or my installation location?


@SB-FM   I tried doing that; unfortunately that doesn't work for me.  Still only launches XCOM 2 with mods, WOTC without.

**Comment by Littlebob86** [comment]
Definitely doesn't work.. I've tried numerous times and full delete and reinstall of xcom 2 :(

**Comment by BTernaryTau** [comment]
@IGdood @Littlebob86 Can you two tell me if your XComModOptions.ini is updating or not?

**Comment by Littlebob86** [comment]
How would I test that?

**Comment by Littlebob86** [comment]
All I know is if I run the base launcher of wotc, the mods work, through the alt launcher, they don't work

**Comment by IGdood** [comment]
@BTernaryTau   It actually is.  I'm trying to compare if there's a difference in how XComModOptions.ini is being updated between the official mod launcher and the alternative.  That should be the determinant in why it's working/not working?

**Comment by Littlebob86** [comment]
I just redownloaded and tried again, mods still not working with the alt launcher, but still with the base launcher :(

The launcher must be working for some people?? Any ideas what can I do to get mine working!? :(

**Comment by sh4dd4r** [comment]
I'm encountering similar or identical issue here and I believe I tracked it down to the Mod Directories setting.

settings.json in this format will cause the game to run without any mods active:
```
  "ModPaths": [
    "C:\\Games\\steamapps\\workshop\\content\\268500"
  ],
```

but if I change it to this (notice trailing backslashes), everything works correctly:
```
  "ModPaths": [
    "C:\\Games\\steamapps\\workshop\\content\\268500\\"
  ],
```

**Comment by BTernaryTau** [comment]
Alright, I think this will solved in the next release. In the meantime, you can try what sh4dd4r did and see if that works.

**Comment by BTernaryTau** [comment]
Can you all let me know if 1.2.1 fixes this issue for you?

**Comment by Spiner909** [comment]
Made an account to help out. Yes, the new version seems to work (had to run it through the vanilla launcher once before, though)
