### ISSUE TITLE
Crash when clicking "Run War of the Chosen" crashes if WOTC is not installed

### ISSUE THREAD

**Issue by AmauryLepicard** [X2CommunityCore/xcom2-launcher#16]
Clicking the button launches an exception "File not found", which is logical if WOTC is not installed.

**Comment by BTernaryTau** [comment]
Hiding that button when WotC isn't installed will come in a future update. In the meantime, you can downgrade to 1.1.3 if you don't care about the other features 1.2.0 added.

**Comment by AmauryLepicard** [comment]
Noted, thanks.
