### ISSUE TITLE
Failed to find default engine .ini file to retrieve My Documents subdirectory to use. Force quitting.

### ISSUE THREAD

**Issue by Morthi** [X2CommunityCore/xcom2-launcher#17]
Everytime I hit run Xcom2 this message pops up.

**Comment by Dragon-32** [comment]
Hopefully you've fixed this? Launch the game using Firaxis' launcher (no mods) and that'll populate the My Games .ini files. Only need to get to the main menu.

Also set key bindings on that first launch as otherwise I find they don't stick.
