### ISSUE TITLE
File -> Search for new mods .. does not do anything.

### ISSUE THREAD

**Issue by Seipherwood** [X2CommunityCore/xcom2-launcher#172]
Using v1.3.2
Clicking Search for new mods does not do anything. I figured it would be a way to refresh the mod list if you had it opened while browsing new mods but it does not seem that way.

**Comment by Xymanek** [comment]
The way I always use it:

* Sub to mod on workshop
* Wait for steam to finish downloading it
* Click search for new mods
* Click "update mod information"

**Comment by Seipherwood** [comment]
It does work that way now that i tried it, but would make more sense to be just 1 button maybe?

**Comment by RevZero** [comment]
Indeed. It is supposed to actually find new mods when you click "Search for new mods".
