### ISSUE TITLE
Processor load up to 20% and huge delays in reaction

### ISSUE THREAD

**Issue by basilbattery** [X2CommunityCore/xcom2-launcher#183]
Great app, but it response to click take about 3-5 sec before it make any visible activity. Can't use it in this way.
Happened after I linked modes (155 items)

**Comment by RevZero** [comment]
Please be more specific. What did you "click"? 
I don't understand what you mean with "after I linked modes".
Can you reproduce it? How exactly?

**Comment by basilbattery** [comment]
Hi

I can reproduce it. This looks like very slow response on any activity. When I check mod it takes about 7-10 sec to show checkmark, swithing between tab 10 sec, etc.
After I linked modes = application didn't find them , I have to show path manually.


________________________________
От: RevZero <notifications@github.com>
Отправлено: среда, 1 апреля 2020 г. 17:11
Кому: X2CommunityCore/xcom2-launcher
Копия: basilbattery; Author
Тема: Re: [X2CommunityCore/xcom2-launcher] Processor load up to 20% and huge delays in reaction (#183)

Please be more specific. What did you "click"?
I don't understand what you mean with "after I linked modes".
Can you reproduce it? How exactly?

**Comment by basilbattery** [comment]
[https://yadi.sk/d/MqudxSY2tWvXHg](url)

Video might be helpful. You can see huge delay between checking and unchecking of mods, screen resizing of Mods tabs. 
Also I see now it happened only on the Mod tab, in profiles and overrides section I have no this kind of slow response.

**Comment by RevZero** [comment]
Hmm, that is really weird. I am not aware that this is a problem for other people. 

I just assume at this point, that your PC isn't just extremely slow, because you obviously can play XCOM with it?!

However, each time an item is (un)checked, there is lots of processing involved, bacause AML reevaluates the conflicts. This involves lots of file accesses and parsing. But it shouldn't be an issue for a modern PC. Maybe something on you machine slows down file access from AML? Potentially some Anti-Virus tool interrupting each access or something?

**Comment by basilbattery** [comment]
I have i4700k, GTX1080ti and SSD. Hardware definitely is not the reason. Also I have no AV software, only Win10 internal. It contain exclusions on all games and user profiles folders, but before sending this issue I turn it off completely to understood what happened without it. No difference. 

I use PerfMon for understanding what happened and do not see any overloading activities from AML on CPU and SDD during this checking, however it makes visilble CPU activities anyway.

This orange lines show this checking very visible.

![Clipboard01](https://user-images.githubusercontent.com/56698101/78234477-dd723580-74df-11ea-807d-afe44730875b.jpg)

**Comment by RevZero** [comment]
Does this also happen when you uncheck all mods and then only check/uncheck a single mod at a time?

**Comment by basilbattery** [comment]
It happened every time I press on mod check, no difference, single or several modes. If I press on single I see same CPU splash.

**Comment by RevZero** [comment]
Maybe I wasn't clear. What I mean is:
1. disable/uncheck ALL mods
2. then enable/disable only a single mod at a time

I want to see if the amount of active mods impacts the delay and if maybe a specific mods causes this (as soon as it is activated).

You may want to join our [Discord](https://discord.gg/QHSVGRn). It is better suited for extended discussion.

**Comment by RevZero** [comment]
@basilbattery Any update on this? Did you try exactly what I suggested in my last comment?

**Comment by basilbattery** [comment]
We had a talk on Discord, and you gave me link to beta, which was slightly more responsive for me. That's was acceptable for mod editing.
