### ISSUE TITLE
Install Question

### ISSUE THREAD

**Issue by yqyjyx** [X2CommunityCore/xcom2-launcher#198]
This is a relatively very stupid question. What does the install guide mean in terms of an xcom2  launcher.exe? I cant seem to find how to start the actual mod launcher itself as there's no .exe file in the folder

**Comment by Dragon-32** [comment]
The .zip you downloaded contains "XCOM2 Launcher.exe", that should have been extracted to the folder you created.

**Comment by RevZero** [comment]
https://github.com/X2CommunityCore/xcom2-launcher/wiki/FAQ#i-downloaded-the-zip-archive-but-there-is-no-application-exe-file

**Comment by RevZero** [comment]
@yqyjyx I will consider this resolved. If you have any further question please ask on our Discord channel.
