### ISSUE TITLE
ModPath entries duplicating on launch

### ISSUE THREAD

**Issue by DallanInvictus** [X2CommunityCore/xcom2-launcher#20]
The code checking for whether a detected mod path is already in the launcher's settings store does not appear to be working correctly, which causes the launcher to re-add the same detected mod paths to the settings (and thereby to the INI), every time it starts.

This would seem harmless but XCOM2 does not handle duplicate mod paths in the INI even **remotely** gracefully, and it can, in my experience, lead to insane load times, crashes, and broken saves.

**Comment by DrKilledalot** [comment]
Had my savegames corrupted by this , if ppl dont know that they have to delete the entries on evry startup this could lead to quite the mass amounts of reports

**Comment by BTernaryTau** [comment]
Are you using version 1.2.1? It should correct this issue.

**Comment by DallanInvictus** [comment]
I'm using 1.2.1 (I re-downloaded it just now to confirm) but this behaviour is still occurring.

**Comment by BTernaryTau** [comment]
Can you paste the text under [Engine.DownloadableContentEnumerator] in your XComEngine.ini?

**Comment by DallanInvictus** [comment]
When I closed the AML I had one set of entries in its Settings (because I prune duplicates regularly now), the next time I ran it it now has two entries in its Settings, and after closing the program the XComEngine.ini is updated to read as follows:

[Engine.DownloadableContentEnumerator]
ModRootDirs=D:\Library\Documents\My games\XCOM2\XComGame\Mods\
ModRootDirs=E:\SteamLibrary\steamapps\workshop\content\268500\
ModRootDirs=D:\Library\Documents\My games\XCOM2\XComGame\Mods
ModRootDirs=E:\SteamLibrary\steamapps\workshop\content\268500

**Comment by daoneandonly747** [comment]
Is there any work around to this? I'm getting the same duplication of the mod directories each time I start up the launcher, even on a fresh installation.

**Comment by RealityMachina** [comment]
Made a fork of the mod to fix that bug here, if you want to use a pre-release version @daoneandonly747 https://github.com/RealityMachina/xcom2-launcher/releases/tag/v1.2.2-RC

**Comment by BTernaryTau** [comment]
Version 1.2.2 has been released and should fix this issue.
