### ISSUE TITLE
Unsubscribe from mod instead of deletion

### ISSUE THREAD

**Issue by RadRussianRus** [X2CommunityCore/xcom2-launcher#209]
When using "Delete / Unsubscribe" function, it will be removed from list. I suggest to add an option to unsubscribe without deletion from mods list, so you can reinstall them at any time.

I've started to work on it here:
https://github.com/RadRussianRus/xcom2-launcher/tree/mod-unsubscribe

But I'm planning to rework this later. My new idea is to add third button or checkbox "Just unsubscribe" in confirmation dialog.

**Comment by Dragon-32** [comment]
When someone unsubscribes from a mod via Steam Workshop doesn't that delete the local files? Presumably the unsubscribe function used by AML simply uses that Steam functionality. So how will you prevent local file deletion when someone launches the Steam client?

**Comment by RadRussianRus** [comment]
It will delete local files, yes. The point is that mod stays in list, so you can resubscribe at any time.

**Comment by Dragon-32** [comment]
OK cool, I was worried that this would have a function labelled Unsubscribe that behaved differently to Steam's Unsubscribe function.
