### ISSUE TITLE
AML fails to start up correctly

### ISSUE THREAD

**Issue by mitchell-van-dort** [X2CommunityCore/xcom2-launcher#212]
Today is the first time this has happened to me (04/06/2020) but whenever is try to start up the program via a desktop shortcut it doesn't load up properly. Maybe i'll get a 1 frame flash of the program then it just disappears. The program appears on my taskbar but when i hover over it to see the display images its just black. I've restarted my computer and checked for windows updates and it still doesnt work. I tried loading it from the file explorer and it still didnt work.
![image](https://user-images.githubusercontent.com/66424803/83762887-63b31f80-a6bb-11ea-9389-8f6c551e9d4f.png)

**Comment by RevZero** [comment]
Please post the following files: `AML.log`, `settings.json` and `error.log` (if existing).

You may have to rename/zip the files to be able to attach them on Github.

**Comment by mitchell-van-dort** [comment]
[settings.zip](https://github.com/X2CommunityCore/xcom2-launcher/files/4730415/settings.zip)

[AML.log](https://github.com/X2CommunityCore/xcom2-launcher/files/4730379/AML.log)

[error.log](https://github.com/X2CommunityCore/xcom2-launcher/files/4730387/error.log)

**Comment by RevZero** [comment]
Hmm, weird. From looking at the log, I can't tell why the user interface isn't showing up properly. 

If you temporarily rename the `settings.json` to `settings_backup.json` for example, does AML start 
afterwards?

**Comment by mitchell-van-dort** [comment]
yep
