### ISSUE TITLE
Wrong encoding of Cyrillic title and description when loaded from Workshop

### ISSUE THREAD

**Issue by RadRussianRus** [X2CommunityCore/xcom2-launcher#215]
When mod title and description is loaded from Steam Workshop, it has wrong character encoding:
![](https://user-images.githubusercontent.com/2903496/84577836-5d622900-adc8-11ea-955f-ec061f3c771f.png)

I think it converts UTF-8 text to Windows-1251 encoding (since I have Russian language by default in Windows).

**Affected versions:** 1.3.2, 1.4.0-beta.3
**How to reproduce:** download any mod with Cyrillic description. If mod description won't load automatically, use "Update" context menu option.
**Mod from screenshot (for easier testing):** https://steamcommunity.com/sharedfiles/filedetails/?id=971469239

**Comment by RevZero** [comment]
From what I can tell, there is currently not much I can do about it, because this is caused by an [issue in the Steamwork.NET API](https://github.com/rlabrecque/Steamworks.NET/pull/347).   
So we have to wait until they release a new API version that contains a respective fix.

**Comment by RadRussianRus** [comment]
Seems that issue is fixed in Steamworks.NET API, since [pull is merged](https://github.com/rlabrecque/Steamworks.NET/pull/347#event-3613700949) and [live in 15.0.0 release](https://github.com/rlabrecque/Steamworks.NET/releases/tag/15.0.0).

**Comment by RevZero** [comment]
Ah, thanks for the info. I will update Steamworks.NET to the latest version with the next release then.
