### ISSUE TITLE
Feature Request: add a button to hide unselected mods.

### ISSUE THREAD

**Issue by AmauryLepicard** [X2CommunityCore/xcom2-launcher#22]
Hi there,
With 292 mods in the launcher, and only 116 activated for Spectrum, looking through the list to find on of them is getting really tedious.
Either adding a button, or adding new categories to the filter system would be awesome.

I'd love to be able to modify it and compile it but I don't have a clue of how to do that. Any tutorial on compiling this?

**Comment by Xebeth** [comment]
You can filter the list by right-clicking the header of the first column:
![image](https://user-images.githubusercontent.com/579504/30931556-532aa738-a3c5-11e7-8bb0-dca328a8069d.png)
The search field can also help you if you know what you're looking for.
