### ISSUE TITLE
Can't delete mod directory

### ISSUE THREAD

**Issue by RadRussianRus** [X2CommunityCore/xcom2-launcher#224]
### Steps to reproduce
1. Add a folder with some mods in it to "Mod Directories" and restart AML.
2. Delete previously added folder from "Mod Directories" and restart AML.

### Expected behavior
Mod directory should be deleted from list.

### Actual behavior
Mod directory is not deleted.

### Additional info
**Version of AML:** 1.4.0
**OS:** Windows 10 x64 1909

**Comment by RevZero** [comment]
@RadRussianRus 
I can not reproduce this.
* Add a folder that contains one mod
* Restart AML -> AML finds new mod
* Delete folder in settings dialog
* Restart AML -> AML warns that one mod can no longer be found 
* Mod folder is no longer listed in settings dialog as expected

**Comment by RadRussianRus** [comment]
Strange. I'll try to test it more throughly when I have time.

**Comment by looplick** [comment]
I'm having the same issue.  I accidentally added the WotC SDK mod directory in the settings and cannot delete it.

**Comment by RevZero** [comment]
Hmm, please post the aml.log file.

**Comment by RevZero** [comment]
Any follow up on this? 

@looplick You mean you were not even able no manually remove the folder from the settings dialog or what exactly?

**Comment by RevZero** [comment]
@RadRussianRus Were you able to test this any further? As mentioned before, I am not able to reproduce this issue. Maybe it only happens under rare circumstances, otherwise there would be more reports.

**Comment by RadRussianRus** [comment]
Sorry, I haven't. Probably it's safe to close now. I'll reopen or create a new issue if I'll test it properly.
