### ISSUE TITLE
Feature request; add a column with the Author name.

### ISSUE THREAD

**Issue by AmauryLepicard** [X2CommunityCore/xcom2-launcher#23]
Hi again
Still with an feature I'd love to be able to add myself, but can't find how to compile the project.

Adding a column would allow to see the mods by a specific author (-bg-, RealityMachina, musashi and others).

**Comment by Xebeth** [comment]
It doesn't look like this info is readily available. It would be doable through the steam web api but this is a bit involved and requires an API key.
