### ISSUE TITLE
Game skips gatecrasher saying mission failed and crashes on next mission.

### ISSUE THREAD

**Issue by arielessar** [X2CommunityCore/xcom2-launcher#238]
Ok, So I know this sounds like something that shouldn't be an issue with the AML launcher but I hope you read it. For whatever reason I can't play the first mission/crash on second when I boot the game using the AML launcher. However, if I launch through the xcom launcher I get no problems. They both use the same mods, I cleared out the xcom config folder in my documents inbetween tests and verified installation for xcom 2. I installed (unzipped rather) a fresh version of AML in case that was the issue and it still presists. I have the AML log file from before I re installed it, and one from after that I am providing below.
[AML (before reinstall).log](https://github.com/X2CommunityCore/xcom2-launcher/files/5491052/AML.before.reinstall.log)
[AML.log](https://github.com/X2CommunityCore/xcom2-launcher/files/5491053/AML.log)

**Comment by RevZero** [comment]
As you pointed out, this is most likely not directly related to AML. 
You probably have more luck asking for help in our #Troubleshooting Discord https://discord.gg/Dr6xVnAHuF channel

**Comment by RevZero** [comment]
Closing because not related to AML.
