### ISSUE TITLE
XCOM2 Launcher.exe - System Error

### ISSUE THREAD

**Issue by jayofgrey** [X2CommunityCore/xcom2-launcher#24]
When starting the AML, I get this error:

![image](https://user-images.githubusercontent.com/32217281/30771652-a94ae032-a001-11e7-82ee-2a08bf5336cd.png)

What may be the problem? 

Thanks.

**Comment by Dragon-32** [comment]
Copy and paste of the error message didn't seem to work.

**Comment by Dragon-32** [comment]
[url=http://steamcommunity.com/app/231160/discussions/0/846955554737962427/#c846956269336455877]Similar error for another program[/url] was fixed by cleaning out and reinstalling .Net

**Comment by RevZero** [comment]
@Xymanek @robojumper : This was a .NET framework issue and nothing specific to AML. How should we deal with issues like this? Maybe put stuff like this into the Wiki as kind of a FAQ and close the issue? 

#42 is similar. Its nothing we can fix, but the comments contain useful information.

**Comment by Xymanek** [comment]
I'm in favor of wiki approach in this case

**Comment by RevZero** [comment]
[Moved to Wiki](../wiki/Troubleshooting#1-2)
