### ISSUE TITLE
AML searches "Config\Config\" for local mod config files

### ISSUE THREAD

**Issue by Triquetra** [X2CommunityCore/xcom2-launcher#241]
For local mods, the config window seems to look in the wrong folder "Config\Config\" instead of "Config\". My main concern here is that the local mod folder is not being parsed correctly during game launch.
![2020-11-24 20_53_10-XCOM Alternative Mod Launcher 1 4 1](https://user-images.githubusercontent.com/195027/100185221-2c6a4200-2e98-11eb-9f03-2877133901ec.png)

**Comment by RevZero** [comment]
That is kind of weird, but you need to be more specific. What is the path to your local mod folder? Please provide all related information. Name of the mod, path to the mod / folder names etc.
Also attach `aml.log` and `settings.json`.

**Comment by Triquetra** [comment]
[AML.log](https://github.com/X2CommunityCore/xcom2-launcher/files/5600074/AML.log)

[settings.json.txt](https://github.com/X2CommunityCore/xcom2-launcher/files/5600076/settings.json.txt)

I've tried a couple of different paths with the same results. The current path, which is reflected in settings.json, is "C:\Games\Steam\steamapps\common\XCOM 2 War of the Chosen SDK\XComGame\Mods"

The name of the mod is zzzMyConfig. It's just a local mod that I'm using to hold my ini config changes. So, the zzzMyConfig folder is located in in the path previously mentioned.

**Comment by RevZero** [comment]
Is the `XComContent.ini` supposed to be in `\Config\Config\XComContent.ini` or should it be `\Config\XComContent.ini`?
Do you still get the error if you move the file one folder down?

**Comment by RevZero** [comment]
OK, so I did some tests and I can confirm that this is a bug. It happens, when the mod folder name contains the word `Config`. When getting the relative ini directories, AML assumes that the first occurrence of `Config` (starting from the mod folder) is the config folder, which is wrong in this case.

Workaround: Rename the mod folder.
