### ISSUE TITLE
Xcom 2 not launching properly from the launcher but launching normally from steam

### ISSUE THREAD

**Issue by DrFishbrain** [X2CommunityCore/xcom2-launcher#242]
[launcher_log.txt](https://github.com/X2CommunityCore/xcom2-launcher/files/5633101/launcher_log.txt)
Normally I'd just go with launching it from steam but when I do that it refuses to use half my mods as they're "Xcom 2 mods and not war of the chosen mods."

**Comment by RevZero** [comment]
Define "not launching properly from the launcher". 
What happens EXACTLY? If it crashes/hangs when loading X2, its likely a mod conflict/issue, not a problem related to AML.

**Comment by DrFishbrain** [comment]
> Define "not launching properly from the launcher".
> What happens EXACTLY? If it crashes/hangs when loading X2, its likely a mod conflict/issue, not a problem related to AML.

What  I mean is that if I load the game normally it works fine and dandy.
When I load it with AML it freezes at some point before starting.

**Comment by deblueseven** [comment]
Can confirm the same issue. Game freezes at some point as well, regardless how long I wait. 

And while the game launcher normally with the regular launcher, several mods don't load due to being tagged as only for Xcom 2 or whatever, I can't actually play the game with the mods I wan't and know SHOULD work with WOTC.

**Comment by RevZero** [comment]
This is very likely only indirectly related to AML. You use AML to load more mods that you are able to with the vanilla launcher. If that doesn't work, its 99% a mod incompatibility or game running out of memory. 

Take a look at the XCOM log files. Also check out the Troubleshooting channel on our [Discord](https://discord.gg/QHSVGRn).

**Comment by RevZero** [comment]
No follow-up from OP.
