### ISSUE TITLE
xcom alternate luancher new release is not working for me

### ISSUE THREAD

**Issue by kenneth7953** [X2CommunityCore/xcom2-launcher#245]
the new alternate mod launcher for xcom 2 war of the chosen is not working for me at all and it keeps freezing up on me and it keeps adding to other files that i feel are not suppose to be there please help! :(

**Comment by RevZero** [comment]
You have to be more specific. What version did you use before? When exactly is it "freezing"? What files you feel "are not suppose to be there"?

You may want to visit our [Discord channel](https://discord.gg/QHSVGRn) and ask for help there.

**Comment by kenneth7953** [comment]
it's freezing up when i got to setting to setup the direct it did it twice to me and it kept adding two other files that I feel ain't suppose to be there.

**Comment by kenneth7953** [comment]
what i mean by freezing up i mean by not responding twice

**Comment by RevZero** [comment]
It freezes when you open the settings dialog? 

> "kept adding two other files"
What file?

Can you make a screenshot? This is all not very helpful.

**Comment by RevZero** [comment]
Missing clarification/feedback from OP.
