### ISSUE TITLE
Category Order (Question/Feature Request)

### ISSUE THREAD

**Issue by Lady-Luck** [X2CommunityCore/xcom2-launcher#25]
How do you reorder categories without going into settings.json and changing the index numbers? It's very time consuming as I'm now up to about 15 categories.

If you can't, then this is a feature request.

**Comment by Dragon-32** [comment]
You can change Category order in the main window:
Settings > Edit

Then move the Categories up and down.

The Categories on the Profile tab are always in the order they were created, no way to change that in the UI I've found.
