### ISSUE TITLE
WOTC crashes on startup

### ISSUE THREAD

**Issue by Alexthemessiah** [X2CommunityCore/xcom2-launcher#29]
Using the 'Run War of the Chosen' button starts the game but before reaching the main menu it crashes. 
![modlaunchercrash](https://user-images.githubusercontent.com/32374960/30991607-9f030136-a49d-11e7-8f79-60beab7d7f90.png)

**Comment by Dragon-32** [comment]
Sounds like a problem with your WoTC install and not the launcher.

Standard troubleshooting advice: DIsable all mods; clear out config folder in My Games; verify files in Steam etc.
