### ISSUE TITLE
Settings > Launcher > Search for updates  -- Has no effect

### ISSUE THREAD

**Issue by Dragon-32** [X2CommunityCore/xcom2-launcher#3]
I believe unchecking the "Search for updates" checkbox means that the Launcher shouldn't scan Steam for mod updates on launch. For me that setting has no effect and whenever I start the launcher I get the "Updating mods" progress bar.

**Comment by robojumper** [comment]
The tooltip of that checkbox says "Search for updates to the launcher when starting".

The progress bar is the launcher re-caching mod information on disk to the json file, and not affected by the checkbox.

**Comment by Dragon-32** [comment]
Ooops
