### ISSUE TITLE
Suggested Change: Duplicate ID/Override Conflicts only when active

### ISSUE THREAD

**Issue by Lady-Luck** [X2CommunityCore/xcom2-launcher#31]
I'm subscribed to a mod that has a beta version with the exact same ID and overrides, obviously you're meant to use one or the other.

It is annoying to have the Mod Manager mark them both red when one is enabled and one is disabled.

**Comment by robojumper** [comment]
The problem with duplicate IDs is literally that they can only be enabled and disabled together (this is written in the warning summary in the other tab!).

Hence, this warning is working as intended.
