### ISSUE TITLE
False Positive: robojumper's Squad Select & Quick Soldier Info

### ISSUE THREAD

**Issue by Lady-Luck** [X2CommunityCore/xcom2-launcher#32]
The mod manager reports these two as conflicting, but -bg-, the author of Quick Soldier Info, attests that they do not and the mod manager is wrong.

Not sure if this is fixable, but, it's good to know about.

**Comment by robojumper** [comment]
The AML has a reason to report that conflict, and it's fixable on -bg-'s side.

**Comment by Lady-Luck** [comment]
Can you describe how it's fixable on -bg-'s side so I can tell him?
