### ISSUE TITLE
Be able to launch AML with epic games instead of steam

### ISSUE THREAD

**Issue by Druivenpasta** [X2CommunityCore/xcom2-launcher#320]
Epic games lately added XCOM 2 and WOTC to it's library, I've got XCOM 2 now, but I can't use AML as it only reacts to steam.
Is it possible to make AML startup also scan for xcom files on epic games?

Suggested solution:
I really have no idea how the .exe now works. 
But I do suggest that you make it work to scan for:
1. XCOM files in epic games files
2. XCOM files if the launcher has acces to the 2k-launcher by fireaxis himself.

**Comment by RevZero** [comment]
There is a way to [make AML work without Steam](https://github.com/X2CommunityCore/xcom2-launcher/wiki/FAQ#is-there-a-way-to-use-aml-without-steam), which seem to work fine with the GoG version of the game. However, judging from our Discord chat, the Epic version causes some issues. 
Duplicate of #181
