### ISSUE TITLE
AML Itself Won't Launch

### ISSUE THREAD

**Issue by Stormhaven13** [X2CommunityCore/xcom2-launcher#322]
Not sure exactly what happened, but the AML refuses to launch at all now. I have been using it as recently as earlier today, but now when I try and launch it, it just sits in my task bar but nothing happens, the launcher doesn't actually open. I did subscribe to a bunch of new mods, but that's the only thing I can imagine that's different.

**Comment by RevZero** [comment]
Please attach àml.log` and `settings.json` from AML folder.

**Comment by Stormhaven13** [comment]
[AML.log](https://github.com/X2CommunityCore/xcom2-launcher/files/8697961/AML.log)

I can't attach the settings.json file, it is not a file type supported by the github writer apparently.

I managed to fix it by doing a completely fresh install, deleted everything in the folder and installed AML again

**Comment by RevZero** [comment]
I do not see anything suspicious in the log file and since you managed to get it working, I will close this issue.
