### ISSUE TITLE
"Missing Mods" Dialog extends off the screen.

### ISSUE THREAD

**Issue by legodude17** [X2CommunityCore/xcom2-launcher#326]
**AML Version:** 1.5

**Description**
I went through my workshop subscriptions and cleaned them out, unsubscribing from around 140 mods. When I launched AML for the first time after this, I was greeted by a dialog that listed these mods, and since there were so many of them it extended off the screen. This meant I could not click "Ok", and the X in the top right corner did not work either. I also could not close the app through the task bar. Ending AML with task manager and relaunching did not work either.

**Attachments**
![image](https://user-images.githubusercontent.com/11205096/175837594-15e85cee-441f-4447-9bb7-fbe1339c375f.png)
[AML.log](https://github.com/X2CommunityCore/xcom2-launcher/files/8987698/AML.log)
[settings.txt](https://github.com/X2CommunityCore/xcom2-launcher/files/8987701/settings.txt)

**Comment by legodude17** [comment]
Update: I worked around it by setting my second monitor to extend the bottom of my first, then could find and click "Yes" on that one.

**Comment by Iridar** [comment]
You could probably just hit Enter.

**Comment by legodude17** [comment]
That is a good point. Still, that should probably be scrollable.

**Comment by RevZero** [comment]
I agree, thanks for reporting.

**Comment by legodude17** [comment]
Makes sense!
