### ISSUE TITLE
Extremely long game launch time

### ISSUE THREAD

**Issue by Jax765** [X2CommunityCore/xcom2-launcher#33]
When launching WOTC via the mod launcher, I tend to have to wait a few minutes for the game to actually boot up to the main menu, and lately it also causes a huge amount of system lag when it's closer to loading. Took a look at xcomengine.ini, and saw this:

[Engine.DownloadableContentEnumerator]
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500

Was told by someone on Reddit that this is caused by the alternative mod launcher, would like to know if this is indeed the case.

**Comment by Dragon-32** [comment]
Interesting. I've launched the game a lot using this. Mine:
[Engine.DownloadableContentEnumerator]
ModRootDirs=E:\Steam\steamapps\common\XCOM 2\XcomGame\Mods\
ModRootDirs=E:\Steam\steamapps\workshop\content\268500\

**Comment by Jax765** [comment]
I tested with the vanilla launcher instead, and this issue doesn't crop up. Less RAM usage, much faster loading, and none of that duplication in the ini file.

**Comment by Dragon-32** [comment]
What happens if you clear out all bar one of those Worksop entries then create a manual Mods directory (same path as mine)?

Wonder if on startup the launcher enumerates the mod directories defined and if there's only one adds it to the list?

I see 92 entries in that list, so it's not a 1:1 mapping based on number of active mods.

BTW, in no way involved in the development of this, BernaryTau is (I think) converting their mods to WoTC and hasn't been round here recently.

**Comment by Jax765** [comment]
I tested removing the duplicate entries, but the game would just automatically add more when using this launcher. Don't think I tested with the manual directory. Will see how that goes.

**Comment by BTernaryTau** [comment]
Are you using version 1.2.1? It should correct this issue.

**Comment by BTernaryTau** [comment]
I'm closing this. Any further conversation should occur in #20.
