### ISSUE TITLE
AML does not honour high DPI setting

### ISSUE THREAD

**Issue by Csimbi** [X2CommunityCore/xcom2-launcher#331]
**AML Version:** 1.5.0

**Description**
I set a high DPI setting 125% in Windows 10, meaning controls - most importantly fonts - should be scaled up.
That ain't the case. AML is unreadable on 4K+ screens.
I also tried forcing it through the compatibility settings - no cigar.

**Attachments**
None at this time.

**Comment by RevZero** [comment]
Thanks for feedback, we already have an issue for this #167 .
