### ISSUE TITLE
Launcher has problems maximizing window

### ISSUE THREAD

**Issue by korgano** [X2CommunityCore/xcom2-launcher#34]
For the past week or two, I've had this problem where I will launch the launcher, the icon will show up in the taskbar, I can mouse over and get a preview image where I can see it updating mods, but I cannot maximize it without going to the Task Manager. 

This is on Windows 10 Creator's Update, 64bit. I also have a .dmp file, if that would help.

**Comment by Dragon-32** [comment]
It's not somehow offscreen is it, korgano?
https://www.howtogeek.com/howto/windows/bring-misplaced-off-screen-windows-back-to-your-desktop-keyboard-trick/

**Comment by korgano** [comment]
Seems like that did the trick. Thanks.
