### ISSUE TITLE
I want to add a "custom name" between "name" and "author" in AML.

### ISSUE THREAD

**Issue by anbai1** [X2CommunityCore/xcom2-launcher#352]
I would like to add a "custom name" between "name" and "author" in AML.
This will make it so that we no longer have to change the original name of the mod in the AML "name" in order to mark up the mod's functionality.
1) Mods can be tagged in any language without breaking the original name.
2) If the mod updates the name, it can update the name normally.
Secondly, I use Simplified Chinese, and about 750 mods. i don't know if it's because i add almost every mod extra name in Chinese, which causes some AML features to fail, such as all mods failing completely, and forcing AML to be turned off upon entering the game, no matter how the settings are changed.
1) I cleaned up the Documents\my games\XCOM2 War of the Chosen\XComGame\Config file and even the Documents\my games\XCOM2 War of the Chosen file.
2) I created and used new AML in other folders and desktop.
3) I turned off Microsoft Defense virus software.
4) Finally, I reinstalled the computer system to get back to normal!
Machine translation was used, I hope you forgive me if it is not accurate.

**Comment by RevZero** [comment]
This is a very specific request with no real benefits.
