### ISSUE TITLE
Stuck on missing mods screen

### ISSUE THREAD

**Issue by memers23** [X2CommunityCore/xcom2-launcher#358]
**AML Version:** 
1.50
**Description**
*Whenever I open AML I get stuck on a missing mods page I can only close via the task manager

**Attachments**
[AML.log](https://github.com/X2CommunityCore/xcom2-launcher/files/13510417/AML.log)
[settings.json](https://github.com/X2CommunityCore/xcom2-launcher/files/13510422/settings.json)
![2023-11-30 (2)](https://github.com/X2CommunityCore/xcom2-launcher/assets/52947080/c0ac2ef5-f1fe-42cc-8370-28bab551ddc5)

**Comment by Iridar** [comment]
Just hit enter or spacebar.

**Comment by memers23** [comment]
ty
