### ISSUE TITLE
game crashing problem

### ISSUE THREAD

**Issue by Romachkachka** [X2CommunityCore/xcom2-launcher#362]
**AML Version:1.5.0** 

**Description**
Hello, soo i just got AML and i tried to make Xcom2 WOTC work with a bunch of mods. the base setup failed and i tried AML
but it crashed in the same fashion, not linked to missing dependencies or conflicting mods, i'm very confused and i would like some help
From what I've seen alot of you seem to be smart pickles, and maybie you can help me decode what's going on 

Thank you in advance

I linked the log :
[Crash Report Xcom2WOTC 01.2024.txt](https://github.com/X2CommunityCore/xcom2-launcher/files/14077363/Crash.Report.Xcom2WOTC.01.2024.txt)

Romachka

**Comment by Dragon-32** [comment]
That's not an AML problem: it's launched the game. That's a problem with the game or the mods you're using.

Read this:
https://old.reddit.com/r/xcom2mods/wiki/mod_troubleshooting#wiki_my_game_crashes_with_mods.21

**Comment by Romachkachka** [comment]
Thank you Dragon, you're right it was a problem with the long war 2 not working with wotc, i should have checked commmon issues of modding, :)
