### ISSUE TITLE
Crashing without any mod conlifct

### ISSUE THREAD

**Issue by deblueseven** [X2CommunityCore/xcom2-launcher#37]
At least, according to the launcher itself, it shows no conflict at all.  Could it be too many cosmetic mods or what?

**Comment by atlanticaccent** [comment]
The alternate launcher is only capable of certain basic conflict checks. 

From the readme: "Basic compatibility checks (duplicate ids, class and screenlistener conflicts)".

This means that it won't detect other conflicts, such as between AI modifications in particular. This means ADVENT Avenger's AI packs will conflict with Dor's A Better Advent, causing a hard crash.

Cosmetic mods and voice packs are memory intensive, but unlikely to cause more than frame drops and stutters.

That is not to say this is an issue with the alternative launcher itself, though the failure to detect your issue could be perceived as a lacking feature. Hope you find your issue!

**Comment by BTernaryTau** [comment]
The launcher can't and isn't intended to catch every possible crash. You'll have to figure out the cause yourself.
