### ISSUE TITLE
Cant boot do to a lack off MSVCR120.dll file

### ISSUE THREAD

**Issue by memers23** [X2CommunityCore/xcom2-launcher#377]
**AML Version:** 
v1.50
**Description**
Wotc will not boot due to there not being a MSVCR120.dll file I have tried reinstalling AML, I verified game files. nothing works

**Attachments**
* *If applicable, add screenshots to help explain your problem.*
* https://github.com/X2CommunityCore/xcom2-launcher/assets/52947080/e8ac960f-facf-42ac-a48a-6e732962cee1

**Comment by RevZero** [comment]
This is not related to AML. Google "xcom 2 msvcrt120.dll" comes up with some result and potential fixes.

**Comment by Iridar** [comment]
Download and install this: https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/
