### ISSUE TITLE
Opening AML causes steam to close.

### ISSUE THREAD

**Issue by somedudeeatingadonut** [X2CommunityCore/xcom2-launcher#389]
**AML Version: 1.51** 

I don't know why, but after updating my AML, whenever I open it, steam closes.

**Comment by RevZero** [comment]
Can you launch XCOM directly from Steam without Steam crashing?
Can you confirm that it still works with a different AML version?

**Comment by somedudeeatingadonut** [comment]
I can launch XCOM 2 normally through steam.
I tried on a fresh install of 1.50 and this still happened, then I went all the way back to 1.40 which is what I had before, and it still happened. Strange because this never happened before updating, but now it happens no matter what.

**Comment by somedudeeatingadonut** [comment]
Reinstalling XCOM 2 fixed it, no clue why that happened though.
