### ISSUE TITLE
Improve Steam mod directory detection

### ISSUE THREAD

**Issue by RevanKaiju** [X2CommunityCore/xcom2-launcher#39]
The launcher won't detect my mods no matter how I put them in or whatever button I push. Does it not detect Steam workshop mods? I'm hoping this would be my answer to getting back the game but it isn't cooperating. It says I need to enter them manually but I have no clue how.

**Comment by Dragon-32** [comment]
Settings menu > Edit...

For me
Base Path = Steam\steamapps\common\XCOM 2

Mod Directories:
Steam\steamapps\common\XCOM 2\XComGame\Mods
Steam\steamapps\workshop\contnet\268500\

**Comment by Hairtrigger83** [comment]
For some reason I don't have Steam\steamapps\common\XCOM 2\XComGame\Mods nor can I seem to find anything like it.  Was able to get the other paths but I can't get it to register any mods.

**Comment by shawarden** [comment]
I have the same issue with no mods appearing:

    "GamePath": "E:\\Games\\SteamLibrary\\steamapps\\common\\XCOM 2",
    "SavePath": null,
    "ModPaths": [
      "E:\\Games\\SteamLibrary\\steamapps\\common\\XCOM 2\\XComGame\\Mods\\",
      "E:\\Games\\SteamLibrary\\steamapps\\workshop\\content\\244160\\"
    ],
    "Arguments": "-review -noRedscreens",
    "CheckForUpdates": false,
    "ShowUpgradeWarning": false,
    "ShowHiddenElements": true,
    "CloseAfterLaunch": false,
    "AutoNumberIndexes": true,
    "UseSpecifiedCategories": true,
    "LastLaunchedWotC": false,
    "Mods": {
      "Entries": {}
    },

**Comment by robojumper** [comment]
@shawarden The second path looks wrong. XCOM 2's Steam App ID is `268500`, not `244160`.
