### ISSUE TITLE
Сrash to desktop on game launch

### ISSUE THREAD

**Issue by Anton-Bauman** [X2CommunityCore/xcom2-launcher#393]
AML Version:1.5.0

I encountered a problem with the game crash on launch via AML. Earlier I used AML with non-Steam version and it worked properly. Now I switched to the Steam version of the game. The clear not-modded game launches without problems. When I add basic Community Highlander + DLC2 with/without other mods for the test and try to launch - I get the crash. Error in the logs is "Failed to find function SubscribeToOnInputForScreen in UIScreenStack XPACK_Shell_Intro.TheWorld:PersistentLevel.XComShellPresentationLayer_0.UIScreenStack_0". I tried to relaunch Steam - useless.
*Default game launcher works properly with mods.
[XCom-CL469133-2024.09.03-23.44.59_Logfile.log](https://github.com/user-attachments/files/16856984/XCom-CL469133-2024.09.03-23.44.59_Logfile.log)
[AML.log](https://github.com/user-attachments/files/16857064/AML.log)
[settings.json](https://github.com/user-attachments/files/16857065/settings.json)

**Comment by tjdouglas** [comment]
Close AML and delete the **settings.json** file and relaunch AML

_"*Default game launcher works properly with mods."_
This can mean that you have a vanilla mod enabled that doesn't work with WotC, the 2K launcher doesn't attempt to launch vanilla mods so it will work (but be misisng the vanilla mods) but AML will run both vanilla and WotC mods so if it is a broken mod it can crash the game.

**Comment by tjdouglas** [comment]
I forgot to add, also delete this folder **\Documents\My Games\XCOM2 War of the Chosen\XComGame\Config** and launch try to launch the game (if it is successful, close the game and launc again to reset the configs)

**Comment by Anton-Bauman** [comment]
> Close AML and delete the **settings.json** file and relaunch AML
> 
> _"*Default game launcher works properly with mods."_ This can mean that you have a vanilla mod enabled that doesn't work with WotC, the 2K launcher doesn't attempt to launch vanilla mods so it will work (but be misisng the vanilla mods) but AML will run both vanilla and WotC mods so if it is a broken mod it can crash the game.

Sorry, it is my stupid mistake actually but anyway AML is not the source of the problem. The topic can be closed.
