### ISSUE TITLE
Unsubscribed mods not going away from alt mod launcher

### ISSUE THREAD

**Issue by deblueseven** [X2CommunityCore/xcom2-launcher#43]
I don't know if my horrible FPS is related to the fact that numerous WOTC mods seem to conflict with old legacy ones and they won't go away even though I've ubsubbed from them on the Workshop.

**Comment by robojumper** [comment]
I think this is intended behavior. Mods will still be shown in the launcher even if unsubscribed, but with a "Not Installed" text in the State column.

**Comment by deblueseven** [comment]
Well the thing is, they get checked whenever I checked the corresponding mod for WOTC... Also other mods have gone away when I've unsubscribed before

**Comment by BTernaryTau** [comment]
This behavior is intentional. To remove a mod from the list, you need to right-click it and select "Delete / Unsubscribe"
