### ISSUE TITLE
Launcher not telling what is conflicting

### ISSUE THREAD

**Issue by deblueseven** [X2CommunityCore/xcom2-launcher#44]
I get extreme lags and geoscape is basically 5 FPS so there is a conflict but the launcher does not say so.

**Comment by robojumper** [comment]
The conflict detection can never detect all possible problems, it only uses a heuristic that catches the most common sources of conflicts.

If you find a reproducable conflict that isn't covered by the launcher, feel free to give us pointers, we'll take a look at improving the conflict detection.

**Comment by deblueseven** [comment]
I see, ok! Well unfortunately I solved it without really knowing how. I just went back to use an earlier mod list and from there enabled a few newer ones. No lag at all!
