### ISSUE TITLE
I'm getting "Please start steam first!" message

### ISSUE THREAD

**Issue by Panderine** [X2CommunityCore/xcom2-launcher#5]
Of course Steam is already open.
Tried running Xcom2 Launcher.exe as admin. Tried adding Xcom2Launcher as non - steam game and launching it from Steam... same error.
Tried loging out an in from steam, as well as killing the bootstrapper and starting steam again... no avail... any idea?

**Comment by BTernaryTau** [comment]
The Steamworks documentation gives 3 reasons why this might happen:

- The Steam client isn't running. A running Steam client is required to provide implementations of the various Steamworks interfaces.
- The Steam client couldn't determine the AppID of the game. Make sure you have steam_appid.txt in your game directory.
- Your application is not running under the same user context as the Steam client, including admin privileges.

Assuming you're not running Steam as a different user or something, I don't think any of these should apply to you, so I'm afraid I don't know how to help you.

**Comment by ckies30** [comment]
I'm also getting this kind of message... I want to try this just to check if my mods have conflicts....
Can I run this with the Crack version? if Yes... How?

**Comment by RevZero** [comment]
@Panderine : Working through old issues here. Did you figure out what the problem was? 

@Xymanek @robojumper: This had most likely nothing to do with AML itself and it is an ancient issue, so I tend to close this.

**Comment by Xymanek** [comment]
Unfortunately, this isn't simply an ancient issue. It keeps cropping up every 1-2 months on reddit or discord

**Comment by RevZero** [comment]
[Moved to Wiki](../wiki/Troubleshooting#1-1)

**Comment by Xymanek** [comment]
I would still vote for not closing this - there have been cases of this error recently on discord

**Comment by RevZero** [comment]
Alright, we should probably investigate this further. It would be really helpful to get some feedback if and how people resolve this. At least if it wasn't one of the obvious reasons of course. But I know, people tend not to report back after a problem is resolved.

**Comment by VolkLogan** [comment]
3 years later and still nothing changed. Problem occured out of nowhere after 1 year of xcom 2 pause .. and no solution to be found anywhere.

**Comment by Xymanek** [comment]
What version of AML are you using?

**Comment by RevZero** [comment]
For documentation purposes: We were not able to resolve the issue for VolkLogan. Process elevation and user context was matching. THis was on Win7, so it might be interesting if the other users that reported this issue also run/ran that OS.

**Comment by VolkLogan** [comment]
In the end i managed to get the launcher working by ... shouting down my Comodo CLaud ANtivirus. 
Version: 1.21.465847.842
Hope this helps some other user in the future.

**Comment by xEyad** [comment]
well i have this problem too.
i can't run the launcher and the AML.log says 
"Failed to detect Steam"
"Shutting down.."
[AML.log](https://github.com/X2CommunityCore/xcom2-launcher/files/3762735/AML.log)

notes:
1- my steam is setup in default location C:\Program Files (x86)\Steam
2- older version XCOM2ModLauncher_1.2.4 is showing same issue too.

**Comment by xEyad** [comment]
Windows defender (windows default antivirus)

**Comment by danarcher** [comment]
I just discovered, whilst cleaning out old profiles saved to the launcher folder, that if I (cough) accidentally move steam_appid.txt along with my old profiles, I receive this error. I wonder if some other people are doing the same thing? In case it helps. Fixed in my case, by putting it back!

Perhaps the launcher could tell you if you've done something this dumb (steam_appid.txt not found in the launcher folder, please put it back or reinstall the launcher), at least it might help diagnose some users' problems.

**Comment by RevZero** [comment]
@danarcher Thanks for the feedback. This has already been improved with AML 1.3.

**Comment by robojumper** [comment]
If #181 is ever implemented, it could be a workaround.

**Comment by WIJOMC** [comment]
Alright fellas I managed to fix the problem with appid.txt thing not appearing, so i could finally get onto aml. The fix i found is when you go to extract the.zip folder containing the xcom2launcher.exe you need to make a folder beforehand and save it in whatever (D:), (C:) local disk you have, but you have to choose the local disk file that does not contain your op system (E.G you did what i did and saved your operating system thing on your ssd so your computer would start up quicker e.t.c). This should let you get onto AML as the xcom2launcher.exe can now find the appid.txt file that your op system was blocking. Sorry if this doesnt make much sense, kinda new to modding for xcom2  but used mods a lot from bl2  and the blcmm launcher which is similar to  AML (Alternative Mod Launcher).
