### ISSUE TITLE
Hangs on last mod

### ISSUE THREAD

**Issue by hellcry37** [X2CommunityCore/xcom2-launcher#50]
Hello,

Sometimes it loads all mods except last one, and hangs there forever. If i close it and run it again all is fine usually.

**Comment by BTernaryTau** [comment]
Does changing what mods are selected have any effect on this, and does this ever happen with the standard launcher?

**Comment by hellcry37** [comment]
No effect what mods are selected. This happens random, I can't reproduce all the time. This happens when scanning new mods with this launcher, nothing to do with official launcher that one does not scan (don't show scan new mods). Anyway this has nothing to do with official launcher.

What is happening is plain simple. I run the xcom2-launcher and sometimes that loading bar from down left part that shows loading / scanning new mods or something like this gets stuck on last mod. Whatever if i have 100 or more like 136 it gets stuck on 100-1 or 136-1. (numbers are just informative) 
Gets stuck only on last mod and only sometimes not always.

After this I close the launcher and run it again. At this point it works ok always.

At the beginning i thought is updating some of the mods, but when this happen it stays like this forever, not like update a mod and finish loading.

**Comment by BTernaryTau** [comment]
Can you still use the launcher after that happens? I believe I've seen that behavior but it's only a visual glitch for me. The launcher's operation is entirely unaffected.

**Comment by RevZero** [comment]
@hellcry37 I know this is an old issue, but do you remember if you had to restart the launcher to resolve it or were you able to just run "Update Mods" again and it worked?

Knowing this would narrow the problem down a lot.

**Comment by hellcry37** [comment]
I always restarted the launcher, I never do update mods, I don't know what that does.

**Comment by RevZero** [comment]
This was very likely fixed in f5653204c2c9ffe0677c81ce92d30f6695c089d9 where the asynchronous mod update processing has been completely revised.
