### ISSUE TITLE
Intermittant Highlander and net connectivity.

### ISSUE THREAD

**Issue by SabinStargem** [X2CommunityCore/xcom2-launcher#51]
I was using the Highlander mod, but features vanished whenever my internet connection went down.  The mod itself was registering - MCM still showed options, but the mods relying on Highlander had no actual effect on the game.  After trying many methods, I ultimately resorted to overwriting the vanilla "CookedPCConsole" folder's contents.  That last resorted works fabulously.

**Comment by Dragon-32** [comment]
Shouldn't this be here:
https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/issues
?

**Comment by SabinStargem** [comment]
Probably both?  After all, the Community Launcher is responsible for turning on and off Highlander, along with talking to Steam for workshop purposes.

Anyhow, just posted the issue on the Highlander github as well.

**Comment by BTernaryTau** [comment]
The launcher's job is merely to tell the game what mods to activate, not how to activate them. If the mod was activating, then the launcher has done its work.
