### ISSUE TITLE
Non-Steam workshop mods not being detected?

### ISSUE THREAD

**Issue by wankerblossom** [X2CommunityCore/xcom2-launcher#52]
I pasted all of my non steam workshop mods into the Mods folder in both
C:\Users\USER\Documents\my games\XCOM2 War of the Chosen\XComGame\Mods
as well as the one in
 C:\Program Files (x86)\Steam\steamapps\common\XCOM 2\XCom2-WarOfTheChosen\XComGame\Mods
and none of them are showing up in the AML. Was i supposed to put them somewhere else?

**Comment by Dragon-32** [comment]
I just have mine in:
Steam\SteamApps\common\XCOM 2\XComGame\Mods

Worked with the base game and with WotC. Make sure you've edited the mod paths in the launcher's configuration screen.

**Comment by RevZero** [comment]
@Xymanek @robojumper  Can you tell if the problem was OP just using the wrong folders? I never really played around with non-workshop mods myself. And when I did, I just used a custom folder and added that to AML in "Settings -> Mod directories". 

In short: Can this be closed?

**Comment by Xymanek** [comment]
`C:\Users\USER\Documents\my games\XCOM2 War of the Chosen\XComGame\Mods` this is wrong, yes
