### ISSUE TITLE
Getting "please start Steam first!" error message

### ISSUE THREAD

**Issue by deblueseven** [X2CommunityCore/xcom2-launcher#57]
I read the other thread, it didn't help me so I make a new one here... I need to troubleshoot my mods because I get a crash but using the normal launcher takes ages every time.

Edit: Ok so I fixed it by reinstalling the latest version, somehow and added it to Steam... However now my game won't start, it launches a window but it does nothing, if I click on it the window just crashes...

Edit 2: Yeah it was just this one mod incompatible with WOTC.

**Comment by deblueseven** [comment]
Ok so I fixed it by reinstalling the latest version, somehow and added it to Steam... However now my game won't start, it launches a window but it does nothing, if I click on it the window just crashes...

**Comment by Dragon-32** [comment]
So it's fixed then, and this Issue can be closed?

**Comment by deblueseven** [comment]
Sure, reinstalling the program fixed it for me.
