### ISSUE TITLE
not finding the exe. file to load this

### ISSUE THREAD

**Issue by roguetiger71** [X2CommunityCore/xcom2-launcher#66]
no exe file located to run this program.. :(

**Comment by Dragon-32** [comment]
Download the .zip from Releases pane:
https://github.com/X2CommunityCore/xcom2-launcher/releases

Extract to folder of your choice.

Run XCOM2 Launcher.exe

**Comment by Dragon-32** [comment]
I guess that fixed it then? 

Can this Issue be Closed?
