### ISSUE TITLE
Show mod dependencies and use them

### ISSUE THREAD

**Issue by yoshimo** [X2CommunityCore/xcom2-launcher#67]
According to robojumper on a recent discord conversation 

> Seems like the API does support that: https://github.com/rlabrecque/Steamworks.NET/blob/d8799444f2ed93556b27bb4b2e9f933c4e543e44/Plugins/Steamworks.NET/autogen/isteamugc.cs#L596-L603
> Would need a bunch of UI work to add it to the AML

I therefore think AML should be able to pull dependency info from steam and display it.
Enabling a mod would also enable its dependencies and warn you if they are missing.

**Comment by Dragon-32** [comment]
Sort of duplicates #56
