### ISSUE TITLE
ModLauncher wont Launch Game

### ISSUE THREAD

**Issue by Blazehomewrecker** [X2CommunityCore/xcom2-launcher#73]
I'm not sure if there is a log dumping to somewhere, or even if it is a crash. But When I launch the game through the mod launcher, with mods enabled or not, just nothing will happen and steam will say i'm no longer playing Xcom without the game window even showing up or windows saying it's crashed. 

When checking with -log it what I assume is initalising, i can see it detect the game settings and it will check all the mods. The last lines I see are dumping name table, Exit: Exiting. and then nothing.

**Comment by robojumper** [comment]
Is this an AML issue? Can you launch the game normally via Steam? Btw, a log file is in 

    %userprofile%/Documents/My Games/XCOM2/XComGame/Logs/Launch.log

or

    %userprofile%/Documents/My Games/XCOM2 War of the Chosen/XComGame/Logs/Launch.log

**Comment by Blazehomewrecker** [comment]
I'm not sure, it launches through steam if I just launch it normally. I checked that more or less first, I launched it through steam, all the way, checked and saw all my save files which i obviously couldn't load and then even launched a new campaign into the first mission to make sure it all works. I did a cache check too. I've used the mod launcher for a long time, but this is the first time I've used it in around 8 or so months and I've never had any problems with it before

**Comment by RevZero** [comment]
@Blazehomewrecker : Did you resolve this somehow?

**Comment by RevZero** [comment]
@Blazehomewrecker: Any news on this issue? Did you compare the log files when launching with Steam and when launching with AML? Did you try AML without any mods enabled?

**Comment by RevZero** [comment]
User specific issue with lack of feedback.
