### ISSUE TITLE
Manually installed mod not working

### ISSUE THREAD

**Issue by DeviathanWhale** [X2CommunityCore/xcom2-launcher#9]
Hi,

The Fallout Ranger Pack was recently accidentally removed from Steam, but thankfully there are still downloads available from other sources.  Unfortunately, these don't seem to be compatible with the AML.  I have a Mods folder inside XComGame, and when I launch with the normal steam mod selector, the mod appears and the items appear in the character creator in game.  However, when I use the AML, the mod isn't even being installed - the size is listed as 0, along with the create and update fields being the unix start time version of 0 (Jan 1 1970).  The state is "Not Loaded" and right clicking and selecting "Show in explorer" brings up my home documents directory rather than the actual mod folder. Anything I can do to fix it?

![ranger pack issue](https://user-images.githubusercontent.com/29765525/27668029-804e6b66-5c33-11e7-83de-b2e9843fc3f1.png)

**Comment by BTernaryTau** [comment]
Others have been reporting similar problems. Can you try following the steps [here](https://www.reddit.com/r/xcom2mods/comments/64mucq/alternative_mod_launcher_now_a_community_project/disroto/) and let me know if you get the same results?

**Comment by DeviathanWhale** [comment]
I tried making the name of the folder the same as the .xcommod file, i.e. "FalloutRangerPack."  It showed up once with the same 0 bytes thing, and then I hid it and restarted the AML which is what I've generally been doing throughout this process.  Then I started it back up and it didn't reappear, so at least something is different.  I also tried adding an entry to settings that I'll attach below.  It seems like it kind of works - my mod count at the bottom when it's updating is 1 higher, and it shows up, but it's still a blank entry with size 0.  That said, if I add the mods folder as an extra place to search for mods (which previously was giving me duplicate blank entries) it now has a preview thumbnail and the 4 relevant configs that can be edited in the AML.  So I'm not sure what to make of that?

[{
            "Index": 283,
            "ID": "FalloutRangerPack",
            "Name": "Fallout Ranger Pack",
            "ManualName": false,
            "Author": "Unknown",
            "Description": "Description of My XCOM 2 Mod.",
            "Path": "D:\\Games\\Steam\\steamapps\\common\\XCOM 2\\XComGame\\Mods\\FalloutRangerPack",
            "Size": 0,
            "isActive": false,
            "isHidden": false,
            "Source": 4,
            "WorkshopID": 720818415,
            "DateAdded": "2017-06-19T18:14:47.5014243-07:00",
            "DateCreated": "1970-01-01T00:00:00",
            "DateUpdated": "1970-01-01T00:00:00",
            "Note": null,
            "Settings": []
          }](url)

**Comment by Dragon-32** [comment]
Does the FalloutRangerPack.XComMod file still have:
publishedFileId=720818415

I think that means AML will use information pulled from the Workshop (which for this mod is nothing). For other mods I've got without Workshop entries I've set the field like so:
publishedFileId=FalloutRangerPack

Admittedly this is for versions prior to AML becoming a community project.

For mods installed in this way I've kind of given up on the Size; Last Update; Date Created fields. I can manually set them via the Inspect tab but they seem to get reset at some point. Maybe if there's a change to the directory contents?

(I open AML by a DOS batch file which backs up my modified INIs and Workshop folder using Robocopy, got burnt a couple of times with mods I use being removed)

**Comment by DeviathanWhale** [comment]
This did fix it!

**Comment by RevZero** [comment]
It is kind of expected behavior isn't it? XComMod contains invalid workshop reference and mod list shows status as "Not Loaded".
Is there something to do here?

**Comment by RevZero** [comment]
Would appreciate feedback if this can be closed @robojumper or anyone else.

**Comment by Xymanek** [comment]
AML shouldn't give erroneous behaviour when failing to load stuff from steam API, just fallback to cached or non-steam version of info
