### ISSUE TITLE
Integrate Sentry.io

### ISSUE THREAD

**Issue by Xymanek** [X2CommunityCore/xcom2-launcher#90]
[Sentry](https://sentry.io) is a service that provides intelligence into exceptions that occur within the application. They have generously sponsored us with an open source license so it's time we start integrating it.

The following issues need to be considered when integrating:

* The integration will need to be disabled in debug builds, otherwise the console will be spammed with useless reports. Probably can use the same check that disables the update checker
* Need to check what information is included in the reports. May need to exclude some information due to privacy concerns
* Need to provide to disable the reporting in case the player doesn't want to share information about their installation
* Need to decide on a way to ID the users. Possible candidates: steam id, machine ID

**Comment by RevZero** [comment]
Regarding identification:
* To get the Steam id, AML has to come far enough to actually get it. So this might not be optimal.
* Do we need one identifier per machine, one per "installation" or both? A user might have two versions of AML in two different folder. The actual folder/location could be the cause of an issue (file permissions, network drive, weird folder name, other files in folder etc.), so it would be better to at least differentiate between those.

**Comment by Xymanek** [comment]
> AML has to come far enough to actually get it. So this might not be optimal

True. Error handling needs to be isolated/independent as much as possible
