### ISSUE TITLE
Avast Antivirus says that version 1.2.4 is infected with IDP.ALEXA.51

### ISSUE THREAD

**Issue by ArkenorOakshadow** [X2CommunityCore/xcom2-launcher#96]
Avast Antivirus says that version 1.2.4 is infected with IDP.ALEXA.51. 

I have no idea if Avast is right or not, but I don't feel like taking my chances.

**Comment by Xymanek** [comment]
Where did you download the AML from?

**Comment by RevZero** [comment]
Several [online virus checks](https://virusscan.jotti.org/de-DE/filescanjob/o8iw6jwzv8) I tested, report nothing suspicious (Avast check included).

[Verify](http://onlinemd5.com), that the MD5 hash of your "XCOM2 Launcher.exe" matches _E74BF7E49AC0030D73FAFADD94138C4E_. If not, the file was changed / has been infected at some point.

**Comment by RevZero** [comment]
This was very likely caused by an infected executable. As pointed out, the online Avast check of the original file is negative.
