### ISSUE TITLE
Can't detect Xcom app on D:/ drive

### ISSUE THREAD

**Issue by bbspecs2** [X2CommunityCore/xcom2-launcher#97]
The mod launcher looks on the C:/ drive and errors when it doesn't find Xcom on the D:/ drive

**Comment by RevZero** [comment]
@bbspecs2  It is unclear to me what exactly you are asking. Please provide some additional details if you still require help.

**Comment by RevZero** [comment]
Closing due to unclear issue and overdue feedback.
